### ISSUE TITLE
Update to TOML 0.5.0

### ISSUE THREAD

**Issue by PallHaraldsson** [wildart/TOML.jl#11]
"As of version 0.5.0, TOML should be considered extremely stable. The goal is for version 1.0.0 to be backwards compatible (as much as humanly possible) with version 0.5.0."

**Comment by PallHaraldsson** [comment]
I first found this other project. It didn't mention this one...

**Comment by wildart** [comment]
#12

**Comment by tpapp** [comment]
Are there plans to support TOML v0.5.0 (and potential future versions) in this package eventually?

**Comment by wildart** [comment]
I do not have time at this moment, but PR is always welcome.

**Comment by tpapp** [comment]
Of course I would be happy to make PRs (I should have started with saying that), but I noticed https://github.com/JuliaLang/Pkg.jl/issues/1011, so I am wondering whether I should wait that out because further changes would just make the merge more difficult. Just please let me know.
