### ISSUE TITLE
FR: Better support of Date-Time and Local date / Local Time

### ISSUE THREAD

**Issue by mkretlow** [wildart/TOML.jl#12]
Hi,
the parser throws an exception if you try to parse a Date-Time formatted as  "2018-01-01 00:00:00Z" instead of "2018-01-01T00:00:00Z", but according to TOML a blank instead 'T' is allowed.

Moreover I would appreciate it very much if support for Date only ("2018-01-01") and perhaps Time only ("08:15:00") would be included in the future. 

Ref: https://github.com/toml-lang/toml#user-content-local-date-time

Thanks, Mike

**Comment by wildart** [comment]
Local dates are TOML v0.5 feature, but this package supports only TOML v0.4. I fixed readability of datetime strings in #13, which is the only thing possible at this moment.

**Comment by mkretlow** [comment]
OK, thanks so far.
