### ISSUE TITLE
Mention relation to Pkg.TOML

### ISSUE THREAD

**Issue by dangirsh** [wildart/TOML.jl#14]
It's unclear how this package relates to `Pkg.TOML` or which one should be used now.

If somebody knows the answer to this, please update the README accordingly.

Thanks!

**Comment by wildart** [comment]
Basically, it's the same package.  Any particular reason?

**Comment by dangirsh** [comment]
Thanks for the quick reply.

Pkg still has issues with unregistered packages. For example: https://github.com/JuliaLang/Pkg.jl/issues/810

Considering `Pkg.TOML` is registered, this makes the existence of an unregistered duplicate (which comes up first in Google) an unnecessary mini-landmine.

They also don't seem to be identical. I can only reproduce [this issue](https://github.com/JuliaLang/Pkg.jl/issues/968) on `Pkg.TOML`.

Are there good reasons to have both?

**Comment by wildart** [comment]
I abandoned this repo for sometime, so it was copied to Pkg during the initial development phase. Later, I caught back with changes.

>Are there good reasons to have both?

I guess Pkg needs to bootstrap TOML package similar to LibGit2, so Pkg has its own copy. Initially, TOML package was a git submodule (from some fork of this repo), but now it's just a copy.

**Comment by ntezak** [comment]
@wildart if you are continuing to develop this, would you consider registering TOML.jl as an official package?

**Comment by wildart** [comment]
That would require deregistering another TOML package from [JuliaRegistries/General](https://github.com/JuliaRegistries/General).
Otherwise, as soon as registry management will be available from Pkg/PkgDev, I'll make a separate registry and list this package there.

**Comment by tknopp** [comment]
It would be really great if this package would be registered. Obviously the current TOML package in METADATA is useless since it cannot be installed in recent Julia versions.

I don't see Julia switching soon from METADATA so that a quick solution would be great.
