### ISSUE TITLE
Advertise TOML.jl (and Julia itself) in TOML Wiki?

### ISSUE THREAD

**Issue by oschulz** [wildart/TOML.jl#16]
We may want to add TOML.jl (and Julia itself) to the list of TOML implementations (and project using TOML): https://github.com/toml-lang/toml/wiki

**Comment by wildart** [comment]
You might want to wait and add a Julia standard library reference later. See https://github.com/JuliaLang/Pkg.jl/issues/1011.

**Comment by fkastner** [comment]
I think this issue can be closed as `Pkg` as well as `TOML.jl` are now listed on that site.

**Comment by oschulz** [comment]
Oh, yes!
