### ISSUE TITLE
improvements to downstream to Pkg.TOML?

### ISSUE THREAD

**Issue by StefanKarpinski** [wildart/TOML.jl#18]
At https://github.com/JuliaLang/Pkg.jl/issues/1011 there is a plan for making the internal `Pkg.TOML` a stdlib in the future, which would make it the de facto TOML package for Julia. However, I want to make sure that we converge this TOML—the original one—with that TOML—the copy—before doing so. What changes here do we need to port over and what's the best strategy for doing so? See also https://github.com/wildart/TOML.jl/issues/14.

**Comment by wildart** [comment]
Right now, packages are not very different, so should start from combining tests, and see differences which need to be addressed. I added you as collaborator to this repo. I guess you'll be able to provide access to anybody who is needed it.

I think it's better to modify this package, so changes would  not be mixed with other Pkg.jl changes.

**Comment by StefanKarpinski** [comment]
> I added you as collaborator to this repo.

Thanks, @wildart!

> I think it's better to modify this package, so changes would not be mixed with other Pkg.jl changes.

Perhaps, although `Pkg.TOML` is pretty isolated and is really just used as a dependency. I'll have to start looking at the differences and get the two to converge. Another way to do it is to just make matching PRs to both bringing them into sync. Once they're identical then it won't matter.
