### ISSUE TITLE
Julia v1.0 compatible release?

### ISSUE THREAD

**Issue by oschulz** [wildart/TOML.jl#19]
TOML feature support in TOML.jl seems to be a more complete than with `Pkg.TOML`. Would it be possible to have a Julia v1.0 compatible release of TOML.jl (so it can be used as a dependency for registered packages)?

**Comment by wildart** [comment]
See JuliaLang/Pkg.jl#1011.

**Comment by oschulz** [comment]
Thanks for link, @wildart !
