### ISSUE TITLE
error message: line number

### ISSUE THREAD

**Issue by PaulXiCao** [wildart/TOML.jl#20]
it would be of great help if an error message for parsing would include the line where an was thrown.

example config file with an error
```toml
var = 1.
```

error message: ``ERROR: LoadError: TOML.ParserError(8, 9, "expected a digit, found `\n`")``

better error message: ``ERROR: LoadError: TOML.ParserError(line: 1, position: 8, 9, "expected a digit, found `\n`")``

**Comment by wildart** [comment]
You example is incorrect. TOML v0.4.0 does not allow an empty  fractional part. A fractional part is a decimal point followed by one or more digits. See https://github.com/toml-lang/toml/tree/v0.4.0#float

**Comment by simeonschaub** [comment]
I just tracked down a problem with `Pkg`, where my `~/.julia/logs/manifest_usage.toml` file got corrupted. It would have been a lot easier to debug, if the line number was included in the error message. Would it also be possible to print the file name if `parsefile` is called?
