### ISSUE TITLE
url to superseded version is broken

### ISSUE THREAD

**Issue by JeffFessler** [wildart/TOML.jl#22]
The README says this package is superseded by
https://github.com/JuliaStdlibs/TOML.jl
but that link is returning an http 404 error.
Where is the official version now?

**Comment by fkastner** [comment]
AFAIU the current plan is to register this package as the official `TOML.jl` and to ship a snapshot for use in `Pkg`.
See this comment by Stefan:

> Since we're moving towards vendoring things that Pkg depends on, we should do that here as well. I.e. set it up so that Pkg depends on a snapshot of the official TOML package rather than making TOML a stdlib. I'm happy to do that if someone else gets things to the point where wildart/TOML.jl and this TOML are identical.
> 
> _Originally posted by @StefanKarpinski in https://github.com/JuliaLang/Pkg.jl/issues/1011#issuecomment-578793879_

Edit:
Apparently a more recent plan is to again try to make `TOML` a stdlib in [#36018](https://github.com/JuliaLang/julia/pull/36018) and [TOMLX.jl](https://github.com/KristofferC/TOMLX.jl).

**Comment by JeffFessler** [comment]
Thanks.  It looks like this issue with the README was addressed by #23 so I am going to close it.
